version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ukraine-help-calculator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qvurt4bfe5oe"
s3_prefix = "ukraine-help-calculator"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
