AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Ukraine help calculator

Globals:
  Function:
    Runtime: python3.9
    Timeout: 10
    Architectures:
      - x86_64
    Layers:
      - !Ref PackagesLayer

Resources:
  GetItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/get_items/
      Handler: app.lambda_handler
      Events:
        GetItems:
          Type: Api
          Properties:
            Path: /get-items
            Method: get

  PackagesLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: Packages
        ContentUri: layers/packages/
        CompatibleRuntimes:
          - python3.9
      Metadata:
        BuildMethod: python3.9

  # DB here

Outputs:
  GetItems:
    Description: "Get items endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-items/"
