AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Ukraine help calculator

Globals:
  Function:
    Runtime: python3.9
    Timeout: 10
    Architectures:
      - x86_64
    Layers:
      - !Ref PackagesLayer
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS,DELETE'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  ItemsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ukraine-help-calculator

  ItemsBucketAllowPublicReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ItemsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Resource:
              - !Join ['/', [!GetAtt [ItemsBucket, Arn], '*']]
            Principal: "*"

  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: UkraineHelpItems
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  GetItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/get_items/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ItemsTable
        - S3ReadPolicy:
            BucketName: !Ref ItemsBucket
      Events:
        GetItems:
          Type: Api
          Properties:
            Path: /get-items/{type}
            Method: get

  PackagesLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: Packages
        ContentUri: layers/packages/
        CompatibleRuntimes:
          - python3.9
      Metadata:
        BuildMethod: python3.9

Outputs:
  GetItems:
    Description: "Get items endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-items/"
